"""Safe local report export engine for JSON, HTML, CSV, Markdown, and PDF."""
from __future__ import annotations

import csv
import html
import io
import json
import re
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, Iterable, List, Tuple


class ExportError(ValueError):
    """Raised when an unsupported or unsafe export is requested."""


class ExportEngine:
    FORMATS = {"json", "html", "csv", "markdown", "pdf"}

    def __init__(self, export_dir: Path) -> None:
        self.export_dir = Path(export_dir).resolve()
        self.export_dir.mkdir(parents=True, exist_ok=True)

    @staticmethod
    def _slug(value: str) -> str:
        cleaned = re.sub(r"[^a-zA-Z0-9._-]+", "-", value.strip()).strip("-._")
        return (cleaned or "report")[:80]

    @staticmethod
    def _generated_stamp() -> str:
        return datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")

    @staticmethod
    def _flatten(value: Any, prefix: str = "") -> List[Tuple[str, str]]:
        rows: List[Tuple[str, str]] = []
        if isinstance(value, dict):
            for key in sorted(value):
                name = f"{prefix}.{key}" if prefix else str(key)
                rows.extend(ExportEngine._flatten(value[key], name))
        elif isinstance(value, list):
            if all(not isinstance(item, (dict, list)) for item in value):
                rows.append((prefix, ", ".join(str(item) for item in value)))
            else:
                for index, item in enumerate(value):
                    rows.extend(ExportEngine._flatten(item, f"{prefix}[{index}]"))
        else:
            rows.append((prefix, "" if value is None else str(value)))
        return rows

    @staticmethod
    def _title(report: Dict[str, Any]) -> str:
        report_type = str(report.get("report_type", "AI Report")).replace("_", " ").title()
        return f"NoorBrain {report_type}"

    def _target(self, report: Dict[str, Any], fmt: str, filename: str | None) -> Path:
        extension = "md" if fmt == "markdown" else fmt
        base = self._slug(filename or f"{report.get('report_type', 'report')}-{self._generated_stamp()}")
        if base.lower().endswith(f".{extension}"):
            base = base[: -(len(extension) + 1)]
        target = (self.export_dir / f"{base}.{extension}").resolve()
        if target.parent != self.export_dir:
            raise ExportError("Unsafe export path")
        return target

    def export(self, report: Dict[str, Any], fmt: str, filename: str | None = None) -> Dict[str, Any]:
        normalized = fmt.lower().strip()
        if normalized not in self.FORMATS:
            raise ExportError(f"Unsupported format: {fmt}")
        target = self._target(report, normalized, filename)
        payload = self.render(report, normalized)
        target.write_bytes(payload)
        return {
            "status": "ok",
            "format": normalized,
            "filename": target.name,
            "path": str(target),
            "size_bytes": target.stat().st_size,
            "generated_at": datetime.now(timezone.utc).isoformat(),
        }

    def render(self, report: Dict[str, Any], fmt: str) -> bytes:
        if fmt == "json":
            return json.dumps(report, indent=2, ensure_ascii=False, default=str).encode("utf-8")
        if fmt == "html":
            return self._html(report).encode("utf-8")
        if fmt == "csv":
            return self._csv(report).encode("utf-8")
        if fmt == "markdown":
            return self._markdown(report).encode("utf-8")
        if fmt == "pdf":
            return self._pdf(report)
        raise ExportError(f"Unsupported format: {fmt}")

    def _html(self, report: Dict[str, Any]) -> str:
        rows = "\n".join(
            f"<tr><th>{html.escape(key)}</th><td>{html.escape(value)}</td></tr>"
            for key, value in self._flatten(report)
        )
        title = html.escape(self._title(report))
        return f"""<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>{title}</title><style>
body{{font-family:system-ui,sans-serif;max-width:1100px;margin:2rem auto;padding:0 1rem;color:#17202a}}
h1{{margin-bottom:.25rem}} .meta{{color:#5d6d7e;margin-bottom:1.5rem}} table{{border-collapse:collapse;width:100%}}
th,td{{border:1px solid #d5d8dc;padding:.55rem;text-align:left;vertical-align:top}} th{{width:34%;background:#f4f6f7}}
</style></head><body><h1>{title}</h1><div class="meta">Generated by NoorBrain Sprint 9.5</div><table>{rows}</table></body></html>"""

    def _csv(self, report: Dict[str, Any]) -> str:
        output = io.StringIO(newline="")
        writer = csv.writer(output)
        writer.writerow(["field", "value"])
        writer.writerows(self._flatten(report))
        return output.getvalue()

    def _markdown(self, report: Dict[str, Any]) -> str:
        lines = [f"# {self._title(report)}", "", "| Field | Value |", "|---|---|"]
        for key, value in self._flatten(report):
            safe_key = key.replace("|", "\\|")
            safe_value = value.replace("|", "\\|").replace("\n", "<br>")
            lines.append(f"| {safe_key} | {safe_value} |")
        return "\n".join(lines) + "\n"

    @staticmethod
    def _pdf_escape(text: str) -> str:
        return text.replace("\\", "\\\\").replace("(", "\\(").replace(")", "\\)")

    def _pdf(self, report: Dict[str, Any]) -> bytes:
        # Minimal dependency-free PDF 1.4 writer. Text is wrapped across pages.
        title = self._title(report)
        source_lines = [title, "Generated by NoorBrain Sprint 9.5", ""]
        source_lines.extend(f"{key}: {value}" for key, value in self._flatten(report))
        wrapped: List[str] = []
        for raw in source_lines:
            text = raw.encode("latin-1", "replace").decode("latin-1")
            while len(text) > 95:
                cut = text.rfind(" ", 0, 95)
                cut = cut if cut > 20 else 95
                wrapped.append(text[:cut])
                text = text[cut:].lstrip()
            wrapped.append(text)
        page_chunks = [wrapped[i:i + 48] for i in range(0, len(wrapped), 48)] or [[title]]

        objects: List[bytes] = []
        objects.append(b"<< /Type /Catalog /Pages 2 0 R >>")
        kids = " ".join(f"{4 + i * 2} 0 R" for i in range(len(page_chunks)))
        objects.append(f"<< /Type /Pages /Kids [{kids}] /Count {len(page_chunks)} >>".encode())
        objects.append(b"<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>")
        for index, chunk in enumerate(page_chunks):
            page_obj = 4 + index * 2
            stream_obj = page_obj + 1
            objects.append(f"<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 3 0 R >> >> /Contents {stream_obj} 0 R >>".encode())
            commands = ["BT", "/F1 10 Tf", "50 750 Td", "13 TL"]
            for line in chunk:
                commands.append(f"({self._pdf_escape(line)}) Tj")
                commands.append("T*")
            commands.append("ET")
            stream = "\n".join(commands).encode("latin-1")
            objects.append(b"<< /Length %d >>\nstream\n" % len(stream) + stream + b"\nendstream")

        out = bytearray(b"%PDF-1.4\n%\xe2\xe3\xcf\xd3\n")
        offsets = [0]
        for number, obj in enumerate(objects, start=1):
            offsets.append(len(out))
            out.extend(f"{number} 0 obj\n".encode())
            out.extend(obj)
            out.extend(b"\nendobj\n")
        xref = len(out)
        out.extend(f"xref\n0 {len(objects)+1}\n".encode())
        out.extend(b"0000000000 65535 f \n")
        for offset in offsets[1:]:
            out.extend(f"{offset:010d} 00000 n \n".encode())
        out.extend(f"trailer\n<< /Size {len(objects)+1} /Root 1 0 R >>\nstartxref\n{xref}\n%%EOF\n".encode())
        return bytes(out)

    def list_exports(self, limit: int = 50) -> List[Dict[str, Any]]:
        files = sorted((p for p in self.export_dir.iterdir() if p.is_file()), key=lambda p: p.stat().st_mtime, reverse=True)
        return [
            {"filename": p.name, "size_bytes": p.stat().st_size, "modified_at": datetime.fromtimestamp(p.stat().st_mtime, timezone.utc).isoformat()}
            for p in files[: max(1, min(200, limit))]
        ]

    def resolve_export(self, filename: str) -> Path:
        safe = self._slug(filename)
        if safe != filename or not safe:
            raise ExportError("Invalid filename")
        target = (self.export_dir / safe).resolve()
        if target.parent != self.export_dir or not target.is_file():
            raise FileNotFoundError(filename)
        return target
